export const genreMap: Record<string, string> = {
    'Fiction': 'Fiction',
    'NonFiction': 'NonFiction',
    'Mystery': 'Mystery',
    'Fantasy': 'Fantasy',
    'Romance': 'Romance',
    'Science Fiction': 'SciFi',
    'Horror': 'Horror',
    'Biography': 'Biography',
    'History': 'History',
    'SelfHelp': 'SelfHelp',
    'Poetry': 'Poetry',
    'Historical Fiction': 'Fiction',
    'Thriller': 'Mystery',
    'Adventure': 'Fiction',
    'Drama': 'Fiction',
    'War': 'Fiction',
    'Cyberpunk': 'SciFi',
    'Tech Thriller': 'Mystery',
    'Sci-Fi Thriller': 'SciFi',
    'Psychological Thriller': 'Mystery',
    'Literary Fiction': 'Fiction',
    'Suspense': 'Mystery',
    'Art Mystery': 'Mystery',
    'Contemporary': 'Fiction',
    'Romantic Comedy': 'Romance',
    'Action Thriller': 'Mystery',
    'Paranormal': 'Fantasy',
  };
  
  export const displayGenres = Object.keys(genreMap).sort();